version: '3'

services:
  mongo:
    container_name: adminmate-express-mongoose
    environment:
      - MONGO_INITDB_DATABASE=demo
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    image: mongo
    ports:
      - '27017:27017'